import { computed, createApp, nextTick, onBeforeUnmount, onMounted, ref } from 'vue';
import Projects from './projects';
import AdminReports from './admin-reports';
import MemberAdmin from './member-admin';
import './style.css';
import './booking.css';
import './sidebar.css';
import './seat-actions.css';
import './booking-seat-state.css';
import './lab-map.css';
import './booking-composer.css';
import './spacious-workspace.css';
import './lab-plan-atmosphere.css';
import './booking-slider.css';

let csrfToken = '';
const api = (path: string, options: RequestInit = {}) => fetch(`/api${path}`, { credentials: 'include', ...options, headers: { 'Content-Type': 'application/json', ...(csrfToken ? { 'X-CSRF-Token': csrfToken } : {}), ...(options.headers || {}) } }).then(async response => { const raw = await response.text(); let payload: any = {}; try { payload = raw ? JSON.parse(raw) : {}; } catch { throw new Error(raw || `请求失败（${response.status}）`); } if (!response.ok) throw new Error(payload.message || payload.detail || payload.error || `请求失败（${response.status}）`); return payload; });
const todayTime = (days = 0, hours = 0) => { const d = new Date(Date.now() + days * 86400000); d.setMinutes(0, 0, 0); d.setHours(d.getHours() + hours); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16); };
const blankSections = () => ({ competition: { title: '', detail: '', collaborators: '无协作同学', omitted: false }, horizontalProject: { title: '', detail: '', collaborators: '无协作同学', omitted: false }, verticalProject: { title: '', detail: '', collaborators: '无协作同学', omitted: false }, learning: { title: '', detail: '', collaborators: '无协作同学', omitted: false }, reading: { title: '', detail: '', omitted: false }, outcome: { title: '', detail: '', url: '', omitted: false }, nextWeek: { title: '', detail: '', collaborators: '无协作同学', omitted: false } });
const reportTitles: Record<string, string> = { competition: '参加竞赛', horizontalProject: '参加教师横向课题', verticalProject: '参加教师纵向课题', learning: '学习内容', reading: '阅读论文、资料和开源项目', outcome: '成果报告', nextWeek: '下周计划' };

const App = {
  components: { Projects, AdminReports, MemberAdmin },
  setup() {
    const user = ref<any>(null), seats = ref<any[]>([]), notices = ref<any[]>([]), active = ref('home'), error = ref(''), toast = ref(''), loading = ref(false), showRegister = ref(false), showPassword = ref(false);
    const statusLabels: Record<string, string> = { UNCONFIRMED: '未确认成员', MOBILE: '流动成员', REVIEW: '考察成员', ACTIVE: '正式成员', OBSERVATION: '旧观察状态', AVAILABLE: '空闲', OCCUPIED: '已占用', PENDING: '待审核', DISABLED: '已停用', FIXED: '固定工位', APPROVED: '已通过', REJECTED: '未通过', CANCELLED: '已取消', OPEN: '待填写', DRAFT: '草稿', SUBMITTED: '已提交', LATE_SUBMITTED: '迟交', MISSED: '未提交', PLANNED: '待开始', AWAITING_DECISION: '待决策', COMPLETED: '已完成', KEEP_SEAT: '保留工位', MOVE_TO_MOBILE: '转为流动成员', EXEMPTED: '已豁免', EXTEND_REVIEW: '已延长考察' };
    let statusTranslator: MutationObserver | null = null;
    const localizeStatuses = () => { const root = document.querySelector('.app-shell'); if (!root) return; const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT); const nodes: Text[] = []; while (walker.nextNode()) nodes.push(walker.currentNode as Text); nodes.forEach(node => { const before = node.nodeValue || ''; const after = before.replace(/\b(UNCONFIRMED|MOBILE|REVIEW|ACTIVE|OBSERVATION|AVAILABLE|OCCUPIED|PENDING|DISABLED|FIXED|APPROVED|REJECTED|CANCELLED|OPEN|DRAFT|SUBMITTED|LATE_SUBMITTED|MISSED|PLANNED|AWAITING_DECISION|COMPLETED|KEEP_SEAT|MOVE_TO_MOBILE|EXEMPTED|EXTEND_REVIEW)\b/g, code => statusLabels[code] || code); if (before === after) return; const parent = node.parentElement; if (parent?.tagName === 'OPTION' && !parent.hasAttribute('value')) parent.setAttribute('value', before.trim()); node.nodeValue = after; }); };
    const login = ref({ studentNo: '', password: '' });
    const registerForm = ref({ studentNo: '', name: '', gender: '男', password: '' });
    const passwordForm = ref({ currentPassword: '', nextPassword: '', confirmPassword: '' });
    const registrations = ref<any[]>([]), members = ref<any[]>([]), applications = ref<any[]>([]), bookings = ref<any[]>([]), reviews = ref<any[]>([]), logs = ref<any[]>([]), overview = ref<any>({});
    const myApplications = ref<any[]>([]), myBookings = ref<any[]>([]), tasks = ref<any[]>([]), circumstances = ref<any[]>([]);
    const selectedSeat = ref<any>(null), selectedTask = ref<any>(null), reportSections = ref<any>(blankSections());
    const reportReviewId = ref(0);
    const openReports = (reviewId = 0) => { reportReviewId.value = reviewId; active.value = 'adminReports'; };
    const assignMember = ref('');
    const joinedProjects = ref<any[]>([]);
    const fillProject = async (section:any, id:string) => { if(!id) return; try { const data = await api('/projects/'+id); section.title = data.project.name; section.collaborators = data.team.filter((m:any)=>m.id!==user.value.id).map((m:any)=>m.name).join('、') || '无协作同学'; } catch(e:any) { say(e.message); } };
    const bookingForm = ref({ seatId: '', startAt: todayTime(1), endAt: todayTime(1, 2) });
    const bookingWindow = ref({ from: todayTime(0), to: todayTime(7) });
    const availability = ref<any>({ seats: [], reservations: [] });
    const circumstanceForm = ref({ type: '考试或保研准备', startAt: todayTime(0), endAt: todayTime(1), description: '', evidenceUrl: '' });
    const reviewForm = ref({ memberId: '', reason: '', requirements: '', startAt: todayTime(0).slice(0, 10), endAt: todayTime(28).slice(0, 10) });
    const availableCount = computed(() => seats.value.filter(s => s.status === 'AVAILABLE' && s.type === 'MOBILE').length);
    const mobileSeats = computed(() => seats.value.filter(s => s.type === 'MOBILE' && s.status !== 'DISABLED'));
    const seatRows = computed(() => [1, 2, 3, 4].map(row => ({ row, west: seats.value.filter(seat => Number(seat.row_no) === row && Number(seat.col_no) <= 4), east: seats.value.filter(seat => Number(seat.row_no) === row && Number(seat.col_no) > 4) })));
    const bookingHours = computed(() => { const start = new Date(bookingForm.value.startAt).getTime(), end = new Date(bookingForm.value.endAt).getTime(); return start && end ? Math.max(0, (end - start) / 3600000) : 0; });
    const bookingConflict = computed(() => { if (!bookingForm.value.seatId || !bookingForm.value.startAt || !bookingForm.value.endAt) return false; const start = new Date(bookingForm.value.startAt).getTime(), end = new Date(bookingForm.value.endAt).getTime(); return availability.value.reservations.some((item: any) => String(item.seat_id) === String(bookingForm.value.seatId) && start < new Date(item.end_at).getTime() && end > new Date(item.start_at).getTime()); });
    const isAdmin = computed(() => user.value?.role === 'ADMIN');
    const selectedTaskCanSubmit = computed(() => Boolean(selectedTask.value?.can_submit));
    const memberStatusCopy = computed(() => ({
      UNCONFIRMED: { title: '账号等待管理员确认', detail: '管理员确认前不能预约流动工位、申请固定工位或提交考察材料。' },
      MOBILE: { title: '你目前是流动成员', detail: '你可以按时间预约流动工位，也可以申请固定工位。' },
      REVIEW: { title: '你目前是考察成员', detail: '你的固定工位正在考察期，请按周完成考察材料。' },
      ACTIVE: { title: '你目前是正式成员', detail: '你拥有固定工位，未处于考察期。' }
    }[user.value?.member_status] || { title: '成员状态加载中', detail: '请刷新以获取最新状态。' }));
    const say = (message: string) => { toast.value = message; setTimeout(() => { if (toast.value === message) toast.value = ''; }, 2800); };
    const loadSeats = async () => { seats.value = await api('/seats'); selectedSeat.value = seats.value.find(seat => seat.id === selectedSeat.value?.id) || (isAdmin.value ? seats.value.find(seat => seat.status === 'AVAILABLE') : null) || null; };
    const loadAvailability = async () => { availability.value = await api(`/seat-bookings/availability?from=${encodeURIComponent(bookingWindow.value.from)}&to=${encodeURIComponent(bookingWindow.value.to)}`); };
    const loadMember = async () => { notices.value = await api('/notifications'); myApplications.value = await api('/seat-applications/my'); myBookings.value = await api('/seat-bookings/my'); tasks.value = await api('/report-tasks/my'); if(selectedTask.value) selectedTask.value = tasks.value.find(t => t.id === selectedTask.value.id) || null; joinedProjects.value = await api('/projects/mine'); circumstances.value = await api('/special-circumstances/my'); await loadAvailability(); nextTick(hideStandaloneBookingNav); };
    const loadAdmin = async () => { [overview.value, registrations.value, members.value, applications.value, bookings.value, reviews.value, logs.value] = await Promise.all([api('/admin/overview'), api('/admin/registrations'), api('/admin/members'), api('/admin/applications'), api('/admin/bookings'), api('/admin/reviews'), api('/admin/audit-logs')]); };
    const refresh = async () => { await loadSeats(); if (!user.value) return; user.value = await api('/me'); if (isAdmin.value) await Promise.all([loadAvailability(), loadAdmin()]); else await loadMember(); };
    const loginAction = async () => { loading.value = true; error.value = ''; try { const result = await api('/auth/login', { method: 'POST', body: JSON.stringify(login.value) }); csrfToken = result.csrfToken || ''; user.value = result.user || await api('/me'); active.value = 'home'; await refresh(); } catch (e: any) { error.value = e.message; } finally { loading.value = false; } };
    const registerAction = async () => { loading.value = true; error.value = ''; try { const result = await api('/auth/register', { method: 'POST', body: JSON.stringify(registerForm.value) }); say(result.message); showRegister.value = false; } catch (e: any) { error.value = e.message; } finally { loading.value = false; } };
    const changePassword = async () => { if (passwordForm.value.nextPassword !== passwordForm.value.confirmPassword) { say('两次输入的新密码不一致'); return; } const changed = await action('/auth/password', 'POST', { currentPassword: passwordForm.value.currentPassword, nextPassword: passwordForm.value.nextPassword }, '密码已更新'); if (changed) { passwordForm.value = { currentPassword: '', nextPassword: '', confirmPassword: '' }; showPassword.value = false; } };
    const logout = async () => { await api('/auth/logout', { method: 'POST' }); csrfToken = ''; user.value = null; selectedTask.value = null; selectedSeat.value = null; reportSections.value = blankSections(); joinedProjects.value = []; active.value = 'home'; await loadSeats(); };
    const pendingActions = new Set<string>();
    const action = async (path: string, method = 'POST', body?: any, success = '操作已完成') => { if(pendingActions.has(path)) return false; pendingActions.add(path); try { await api(path, { method, body: body === undefined ? undefined : JSON.stringify(body) }); say(success); await refresh(); return true; } catch (e: any) { say(e.message); return false; } finally { pendingActions.delete(path); } };
    const applySeat = () => { if (!selectedSeat.value) return; action('/seat-applications', 'POST', { seatId: selectedSeat.value.id, reason: '希望在实验室持续开展项目和学习。' }, '固定工位申请已提交'); };
    const isSectionOmitted = (section: any) => Boolean(section?.omitted) || Object.entries(section || {}).filter(([key]) => key !== 'omitted').every(([, value]) => String(value ?? '') === '无');
    const toggleSectionOmitted = (section: any) => {
      if (isSectionOmitted(section)) {
        section.omitted = false;
        Object.keys(section).forEach(key => { if (key !== 'omitted') section[key] = key === 'collaborators' ? '无协作同学' : ''; });
      } else {
        section.omitted = true;
        Object.keys(section).forEach(key => { if (key !== 'omitted') section[key] = '无'; });
      }
    };
    const saveReport = (mode: string) => { if (!selectedTask.value) return; if (!selectedTaskCanSubmit.value) { say('下一周周报尚未开始，当前只能填写当周材料'); return; } action(`/report-tasks/${selectedTask.value.id}/report`, 'POST', { mode, sections: reportSections.value }, mode === 'save' ? '周报草稿已保存' : '周报已提交'); };
    const openTask = (task: any) => { selectedTask.value = task; try { reportSections.value = task.sections_json ? JSON.parse(task.sections_json) : blankSections(); } catch { reportSections.value = blankSections(); } Object.values(reportSections.value).forEach((section: any) => { if (!('omitted' in section)) section.omitted = isSectionOmitted(section); }); active.value = 'reports'; };
    const hideStandaloneBookingNav = () => { if (isAdmin.value) return; document.querySelectorAll('.sidebar button').forEach(button => { if (button.textContent?.includes('流动工位预约')) (button as HTMLElement).style.display = 'none'; }); };
    const displayBookingTime = (value: string) => String(value || '').replace('T', ' ').slice(5, 16);
    const bookingStateForSeat = (seatId: number) => {
      const now = Date.now();
      const records = (availability.value.reservations || []).filter((item: any) => String(item.seat_id) === String(seatId) && item.status === 'APPROVED');
      if (records.some((item: any) => new Date(item.start_at).getTime() <= now && new Date(item.end_at).getTime() > now)) return 'in-use';
      if (records.some((item: any) => new Date(item.start_at).getTime() > now)) return 'reserved';
      return '';
    };
    const bookingLabelForSeat = (seatId: number) => ({ 'in-use': '使用中', reserved: '已预约' }[bookingStateForSeat(seatId)] || '流动工位');
    const escapeHtml = (value: unknown) => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]!));
    const attachMemberSeatActions = () => {
      const detail = document.querySelector('.seat-detail') as HTMLElement | null;
      if (!detail || !selectedSeat.value || selectedSeat.value.type !== 'MOBILE' || selectedSeat.value.status !== 'AVAILABLE') return;
      document.querySelector('.seat-page .member-seat-actions')?.remove();
      const seatReservations = isAdmin.value ? bookings.value.filter((item: any) => ['PENDING', 'APPROVED'].includes(item.status)) : (availability.value.reservations || []);
      const reservedSlots = seatReservations.filter((item: any) => String(item.seat_id) === String(selectedSeat.value.id)).map((item: any) => {
        const member = isAdmin.value && item.name ? `<strong>${escapeHtml(item.name)}</strong>` : (item.current_user_name ? `<strong>当前使用：${escapeHtml(item.current_user_name)}</strong>` : '');
        const status = isAdmin.value ? (item.status === 'PENDING' ? '待审核' : '已通过') : (item.mine ? '我的预约' : '已占用');
        return `<article class="seat-slot${item.mine ? ' mine' : ''}"><span>${displayBookingTime(item.start_at)} 至 ${displayBookingTime(item.end_at)}</span><small>${status}</small>${member}</article>`;
      }).join('');
      const host = document.createElement('div');
      host.className = 'member-seat-actions';
      if (isAdmin.value) {
        host.innerHTML = `<section class="seat-slot-section"><div class="seat-slot-heading"><h3>该工位预约</h3><span>可查看预约成员</span></div><div class="seat-slot-list">${reservedSlots || '<p class="seat-slot-empty">未来 7 天暂无有效预约。</p>'}</div></section>`;
        detail.appendChild(host);
        return;
      }
      const localDate = (offset: number) => { const date = new Date(); date.setDate(date.getDate() + offset); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 10); };
      const dates = Array.from({ length: 8 }, (_, index) => { const value = localDate(index); const date = new Date(`${value}T12:00`); return { value, label: index === 0 ? '今天' : index === 1 ? '明天' : `周${'日一二三四五六'[date.getDay()]}`, date: `${date.getMonth() + 1}/${date.getDate()}` }; });
      const times = Array.from({ length: 29 }, (_, index) => { const minutes = 8 * 60 + index * 30; return `${String(Math.floor(minutes / 60)).padStart(2, '0')}:${String(minutes % 60).padStart(2, '0')}`; });
      const startDate = bookingForm.value.startAt.slice(0, 10) || localDate(0);
      const startTime = bookingForm.value.startAt.slice(11, 16) || '09:00';
      const endTime = bookingForm.value.endAt.slice(11, 16) || '11:00';
      const dateIndex = Math.max(0, dates.findIndex(day => day.value === startDate));
      const startIndex = Math.max(0, times.indexOf(startTime));
      const endIndex = Math.max(0, times.indexOf(endTime));
      host.classList.add('booking-drawer');
      host.innerHTML = `<section class="booking-drawer-head"><div><p>流动工位预约</p><h2>${escapeHtml(selectedSeat.value.code)}</h2></div><span>每一格为 30 分钟</span></section><div class="booking-drawer-grid"><section class="booking-availability"><div class="seat-slot-heading"><h3>已预约时段</h3><span>仅显示占用</span></div><div class="seat-slot-list">${reservedSlots || '<p class="seat-slot-empty">未来 7 天暂无预约。</p>'}</div><button type="button" class="outline-action" data-action="apply">申请为固定工位</button></section><section class="booking-builder"><div class="booking-builder-head"><h3>选择预约时段</h3><span>单次不超过 4 小时</span></div><label class="range-field"><span>预约日期 <b data-output="date"></b></span><input data-field="date" type="range" min="0" max="7" step="1" value="${dateIndex}"><small>今天 <i></i> 7 天后</small></label><label class="range-field"><span>开始时间 <b data-output="start"></b></span><input data-field="start" type="range" min="0" max="28" step="1" value="${startIndex}"><small>08:00 <i></i> 22:00</small></label><label class="range-field"><span>结束时间 <b data-output="end"></b></span><input data-field="end" type="range" min="0" max="28" step="1" value="${endIndex}"><small>08:00 <i></i> 22:00</small></label><p class="booking-feedback" data-feedback></p><button type="button" class="primary-action" data-action="book">提交预约</button></section></div>`;
      document.querySelector('.seat-page')?.appendChild(host);
      const dateSlider = host.querySelector('[data-field="date"]') as HTMLInputElement;
      const startSlider = host.querySelector('[data-field="start"]') as HTMLInputElement;
      const endSlider = host.querySelector('[data-field="end"]') as HTMLInputElement;
      const feedback = host.querySelector('[data-feedback]') as HTMLParagraphElement;
      const submit = host.querySelector('[data-action="book"]') as HTMLButtonElement;
      const sync = () => {
        const selectedDate = dates[Number(dateSlider.value)].value;
        const start = `${selectedDate}T${times[Number(startSlider.value)]}`, end = `${selectedDate}T${times[Number(endSlider.value)]}`;
        const hours = (new Date(end).getTime() - new Date(start).getTime()) / 3600000;
        const conflict = (availability.value.reservations || []).some((item: any) => String(item.seat_id) === String(selectedSeat.value.id) && new Date(start).getTime() < new Date(item.end_at).getTime() && new Date(end).getTime() > new Date(item.start_at).getTime());
        bookingForm.value = { seatId: String(selectedSeat.value.id), startAt: start, endAt: end };
        const valid = hours > 0 && hours <= 4 && !conflict;
        submit.disabled = !valid;
        feedback.className = `booking-feedback${valid ? '' : ' bad'}`;
        feedback.textContent = conflict ? '该时段已有预约，请选择其他时间。' : hours <= 0 ? '结束时段必须晚于开始时段。' : hours > 4 ? '单次预约不能超过 4 小时。' : `${hours.toFixed(1)} 小时，${new Date(start).getTime() > Date.now() + 3 * 86400000 ? '将提交管理员审批' : '将自动通过'}。`;
        (host.querySelector('[data-output="date"]') as HTMLElement).textContent = `${dates[Number(dateSlider.value)].label} ${dates[Number(dateSlider.value)].date}`;
        (host.querySelector('[data-output="start"]') as HTMLElement).textContent = times[Number(startSlider.value)];
        (host.querySelector('[data-output="end"]') as HTMLElement).textContent = times[Number(endSlider.value)];
      };
      dateSlider.oninput = sync;
      startSlider.oninput = sync;
      endSlider.oninput = sync;
      (host.querySelector('[data-action="apply"]') as HTMLButtonElement).onclick = () => applySeat();
      submit.onclick = async () => { if (submit.disabled) return; const booked = await action('/seat-bookings', 'POST', bookingForm.value, '预约已提交'); if (booked) nextTick(attachMemberSeatActions); };
      sync();
    };
    const selectSeat = (seat: any) => {
      selectedSeat.value = seat;
      assignMember.value = '';
      if (seat.type !== 'MOBILE') return nextTick(attachMemberSeatActions);
      bookingForm.value.seatId = String(seat.id);
      loadAvailability().then(() => nextTick(attachMemberSeatActions)).catch(e => say(e.message));
    };
    const restoreSession = async () => { try { user.value = await api('/me'); const csrf = await api('/csrf'); csrfToken = csrf.csrfToken || ''; await refresh(); } catch { user.value = null; csrfToken = ''; } };
    onMounted(() => { loadSeats().catch(e => error.value = e.message); restoreSession(); nextTick(() => { localizeStatuses(); hideStandaloneBookingNav(); }); statusTranslator = new MutationObserver(localizeStatuses); statusTranslator.observe(document.querySelector('#app')!, { childList: true, subtree: true, characterData: true }); });
    onBeforeUnmount(() => statusTranslator?.disconnect());
    const cancelReview = (row:any) => { const reason = window.prompt('取消 '+row.name+' 的本次考察？固定工位和历史材料保留。请输入取消原因：'); if(!reason?.trim()) return; action('/admin/reviews/'+row.id+'/cancel','POST',{reason:reason.trim()},'考察已取消，固定工位和历史材料保留'); };
    return { cancelReview,reportReviewId, openReports, api, joinedProjects, fillProject, user, seats, seatRows, notices, active, error, toast, loading, showRegister, showPassword, login, registerForm, passwordForm, registrations, members, applications, bookings, reviews, logs, overview, myApplications, myBookings, tasks, circumstances, selectedSeat, selectedTask, selectedTaskCanSubmit, reportSections, reportTitles, assignMember, memberStatusCopy, bookingForm, bookingWindow, availability, bookingHours, bookingConflict, circumstanceForm, reviewForm, availableCount, mobileSeats, isAdmin, loginAction, registerAction, changePassword, logout, action, applySeat, saveReport, openTask, selectSeat, toggleSectionOmitted, isSectionOmitted, loadAvailability, refresh, bookingStateForSeat, bookingLabelForSeat };
  },
  template: `
  <main class="app-shell">
    <header class="topbar"><a class="brand" href="#" @click.prevent="active='home'"><span class="brand-mark"><i></i><i></i><i></i><i></i></span><span><strong>实验室管理系统</strong><small>MEMBER · SEAT · REVIEW</small></span></a><div v-if="user" class="top-actions"><span class="identity"><i></i>{{ user.name }} · {{ isAdmin ? '管理员' : user.member_status }}</span><button class="text-btn" @click="showPassword=true">修改密码</button><button class="text-btn" @click="logout">退出</button></div><span class="topbar-state" v-else>工位与成员管理平台</span></header>
    <div v-if="toast" class="toast">{{ toast }}</div>
    <div v-if="showPassword" class="modal-backdrop" @click.self="showPassword=false"><section class="password-modal"><button class="modal-close" @click="showPassword=false">×</button><p class="eyebrow">ACCOUNT SECURITY</p><h2>修改密码</h2><p>请使用至少 10 位的新密码，并妥善保管。</p><label>当前密码<input v-model="passwordForm.currentPassword" type="password" autocomplete="current-password"></label><label>新密码<input v-model="passwordForm.nextPassword" type="password" minlength="10" autocomplete="new-password"></label><label>确认新密码<input v-model="passwordForm.confirmPassword" type="password" minlength="10" autocomplete="new-password"></label><button class="primary-action" :disabled="!passwordForm.currentPassword||passwordForm.nextPassword.length<10||!passwordForm.confirmPassword" @click="changePassword">更新密码</button></section></div>
    <section v-if="!user" class="welcome-layout"><div class="intro-copy"><p class="eyebrow">LABORATORY OPERATIONS</p><h1>实验室成员与<br><em>工位管理系统</em></h1><p class="intro-text">统一处理成员注册、固定工位、流动工位预约、考察周报与人工决策。</p><div class="seat-summary"><div><b>{{ availableCount }}</b><span>空闲流动工位</span></div><div><b>32</b><span>主实验室工位</span></div><div><b>50+</b><span>并发使用目标</span></div></div></div><section class="login-panel"><template v-if="!showRegister"><div class="login-heading"><span class="line"></span><p>账号登录</p></div><h2>登录工作台</h2><label>学号<input v-model="login.studentNo" placeholder="请输入学号" @keyup.enter="loginAction"></label><label>密码<input v-model="login.password" type="password" placeholder="请输入密码" @keyup.enter="loginAction"></label><button class="primary-action" :disabled="loading" @click="loginAction">{{ loading?'正在验证…':'登录' }}</button><p class="form-error" v-if="error">{{ error }}</p><button class="register-link" @click="showRegister=true">注册实验室成员账号</button></template><template v-else><div class="login-heading"><span class="line"></span><p>成员注册申请</p></div><h2>提交成员申请</h2><label>学号<input v-model="registerForm.studentNo" placeholder="学号"></label><label>姓名<input v-model="registerForm.name" placeholder="真实姓名"></label><label>性别<select v-model="registerForm.gender"><option>男</option><option>女</option><option>其他</option></select></label><label>密码<input v-model="registerForm.password" type="password" minlength="8" placeholder="设置至少 8 位密码"></label><button class="primary-action" :disabled="loading" @click="registerAction">提交审核申请</button><p class="form-error" v-if="error">{{ error }}</p><button class="register-link" @click="showRegister=false">返回登录</button></template></section></section>
    <section v-if="!user" class="space-preview"><div class="preview-heading"><div><p class="eyebrow">LAB MAP</p><h2>主实验室 · 工位平面图</h2></div><div class="legend"><span><i class="available-key"></i>空闲</span><span><i class="occupied-key"></i>已占用</span><span><i class="pending-key"></i>待审核</span></div></div><div class="room"><div class="north-wall"><span>北侧</span><b>入口 · 门</b><span>北侧</span></div><div class="seat-plan-scroll"><div class="seat-plan"><div v-for="row in seatRows" :key="row.row" class="seat-row"><div class="seat-bank"><button v-for="seat in row.west" :key="seat.id" class="seat" :class="[seat.status.toLowerCase(),{'mobile':seat.type==='MOBILE'}]"><span>{{ seat.code }}</span><small>{{ seat.type==='MOBILE'?'流动':(seat.occupant_name||'可申请') }}</small></button></div><div class="central-aisle"><span>通道</span></div><div class="seat-bank"><button v-for="seat in row.east" :key="seat.id" class="seat" :class="[seat.status.toLowerCase(),{'mobile':seat.type==='MOBILE'}]"><span>{{ seat.code }}</span><small>{{ seat.type==='MOBILE'?'流动':(seat.occupant_name||'可申请') }}</small></button></div></div></div></div><div class="south-wall"><span>南侧 · 窗户</span><i></i><i></i><i></i><i></i><span>南侧 · 窗户</span></div></div></section>
    <section v-else class="workspace"><aside class="sidebar"><p class="sidebar-caption">{{ isAdmin?'MANAGEMENT':'MEMBER SPACE' }}</p><button :class="{active:active==='home'}" @click="active='home'">⌂　工作台</button><template v-if="isAdmin"><button :class="{active:active==='members'}" @click="active='members'">◎　成员管理</button><button :class="{active:active==='seats'}" @click="active='seats'">▦　工位与分配</button><button :class="{active:active==='applications'}" @click="active='applications'">◌　申请与预约 <b>{{ applications.length+bookings.filter(b=>b.status==='PENDING').length }}</b></button><button :class="{active:active==='reviews'}" @click="active='reviews'">◷　考察与决策</button><button :class="{active:active==='adminReports'}" @click="openReports()">▤　报告查询</button><button :class="{active:active==='logs'}" @click="active='logs'">≡　审计日志</button></template><template v-else><button :class="{active:active==='seats'}" @click="active='seats'">▦　工位申请</button><button :class="{active:active==='booking'}" @click="active='booking'">◌　流动工位预约</button><button :class="{active:active==='reports'}" @click="active='reports'">◷　考察周报 <b>{{ tasks.filter(t=>!['SUBMITTED','LATE_SUBMITTED'].includes(t.status)).length }}</b></button><button :class="{active:active==='special'}" @click="active='special'">＋　特殊情况</button><button :class="{active:active==='notices'}" @click="active='notices'">✦　站内信 <b>{{ notices.filter(n=>!n.read_flag).length }}</b></button></template><button :class="{active:active==='projects'}" @click="active='projects'">◇　项目团队</button></aside>
      <section class="content">
        <AdminReports v-if="active==='adminReports' && isAdmin" :request="api" :review-id="reportReviewId" />
        <Projects v-if="active==='projects'" :request="api" :user="user" :members="members" @changed="refresh" />
        <div v-if="active==='home'" class="page-head"><div><p class="eyebrow">{{ isAdmin?'LAB CONTROL CENTER':'MY WORKSPACE' }}</p><h1>{{ isAdmin?'实验室运行概览':'你好，'+user.name+'。' }}</h1><p>{{ isAdmin?'今天的审批、工位和考察状态都在这里。':'查看你的工位、周报任务和预约记录。' }}</p></div><button class="outline-action" @click="refresh">刷新数据　↻</button></div>
        <div v-if="active==='home' && isAdmin" class="metric-grid"><article><span>空闲流动工位</span><b>{{ overview.availableSeats||0 }}</b><small>可直接分配或开放申请</small></article><article><span>待审核注册</span><b>{{ overview.pendingRegistrations||0 }}</b><small>新成员注册申请</small></article><article><span>进行中考察</span><b>{{ overview.activeReviews||0 }}</b><small>须按周提交材料</small></article><article><span>待人工决策</span><b>{{ overview.awaitingDecision||0 }}</b><small>考察到期成员</small></article></div>
        <div v-if="active==='home' && !isAdmin" class="member-home"><div class="info-banner"><p class="eyebrow">MEMBER STATUS</p><h2>{{ memberStatusCopy.title }}</h2><p>{{ memberStatusCopy.detail }}</p></div><div class="task-list"><h2>近期事项</h2><article v-for="task in tasks.slice(0,4)" :key="task.id"><span class="dot"></span><div><b>第 {{ task.period_index }} 周考察材料</b><p>截止：{{ task.due_at }} · {{ task.status }}</p></div><button @click="openTask(task)">填写</button></article><p v-if="!tasks.length" class="empty">暂无考察周报任务</p></div></div>
        <MemberAdmin v-if="active==='members' && isAdmin" :request="api" :user="user" @changed="refresh" />
        <section v-if="active==='seats'"><div class="page-head small"><div><p class="eyebrow">SEAT OPERATIONS</p><h1>{{isAdmin?'工位与直接分配':'固定工位申请'}}</h1><p>{{isAdmin?'点击工位后直接调整类型、分配成员或释放固定工位。':'点击流动工位查看预约时段、申请固定工位或直接预约。'}}</p></div></div><div class="seat-page"><div class="room admin-room"><div class="north-wall"><span>北侧入口</span><b>门</b></div><div class="floor-plan"><button v-for="seat in seats" :key="seat.id" class="seat" :class="[seat.status.toLowerCase(),bookingStateForSeat(seat.id),{'aisle-edge':seat.col_no===4,'mobile':seat.type==='MOBILE','selected':selectedSeat?.id===seat.id}]" @click="selectSeat(seat)"><span>{{seat.code}}</span><small>{{seat.type==='MOBILE'?bookingLabelForSeat(seat.id):(seat.occupant_name||seat.status)}}</small></button></div><div class="south-wall"><span>南侧落地窗</span><i></i><i></i><i></i></div></div><aside class="seat-detail" v-if="selectedSeat"><p class="eyebrow">{{selectedSeat.code}}</p><h2>{{selectedSeat.type==='MOBILE'?'流动工位':'固定工位'}}</h2><p>状态：<b>{{selectedSeat.status}}</b></p><p>当前成员：<b>{{selectedSeat.occupant_name||'无'}}</b></p><template v-if="isAdmin"><label>工位用途<select :value="selectedSeat.type" @change="action('/admin/seats/'+selectedSeat.id+'/type','POST',{type:$event.target.value},'工位类型已更新')"><option value="FIXED">固定工位</option><option value="MOBILE">流动工位</option><option value="DISABLED">停用</option></select></label><label v-if="selectedSeat.status==='AVAILABLE'">直接分配给<select v-model="assignMember"><option value="">选择成员</option><option v-for="m in members.filter(m=>m.approved&&m.role==='MEMBER'&&!m.seat_code)" :value="m.id">{{m.name}} · {{m.student_no}}</option></select></label><button v-if="selectedSeat.status==='AVAILABLE'" class="primary-action" :disabled="!assignMember" @click="action('/admin/seats/'+selectedSeat.id+'/assign','POST',{memberId:assignMember},'固定工位已分配')">直接分配</button><button v-if="selectedSeat.status==='OCCUPIED'" class="danger-action" @click="action('/admin/seats/'+selectedSeat.id+'/release','POST',{reason:'管理员释放'},'已释放工位并转为流动成员')">释放并转流动成员</button></template><button v-else-if="selectedSeat.status==='AVAILABLE'&&selectedSeat.type==='FIXED'" class="primary-action" @click="applySeat">提交工位申请</button></aside></div></section>
        <section v-if="active==='applications' && isAdmin"><div class="page-head small"><div><p class="eyebrow">REQUEST CENTER</p><h1>申请与预约审核</h1></div></div><div class="split-panels"><article class="panel"><h2>固定工位申请 <span>{{applications.length}}</span></h2><div v-for="row in applications" :key="row.id" class="list-row"><div><b>{{row.name}} · {{row.code}}</b><p>{{row.reason||'未填写理由'}}</p></div><div><button class="approve" @click="action('/admin/applications/'+row.id+'/approve','POST',{},'已通过工位申请')">通过</button><button class="reject" @click="action('/admin/applications/'+row.id+'/reject','POST',{},'已拒绝工位申请')">拒绝</button></div></div><p class="empty" v-if="!applications.length">暂无待审核申请</p></article><article class="panel"><h2>流动工位预约 <span>{{bookings.filter(b=>b.status==='PENDING').length}}</span></h2><div v-for="row in bookings.filter(b=>b.status==='PENDING')" :key="row.id" class="list-row"><div><b>{{row.name}} · {{row.code}}</b><p>{{row.start_at}} 至 {{row.end_at}}</p></div><div><button class="approve" @click="action('/admin/bookings/'+row.id+'/approve','POST',{},'已批准预约')">通过</button><button class="reject" @click="action('/admin/bookings/'+row.id+'/reject','POST',{},'已拒绝预约')">拒绝</button></div></div><p class="empty" v-if="!bookings.filter(b=>b.status==='PENDING').length">暂无待审核预约</p><h3 class="sub-head">已批准预约</h3><div v-for="row in bookings.filter(b=>b.status==='APPROVED')" :key="'approved-'+row.id" class="list-row"><div><b>{{row.name}} · {{row.code}}</b><p>{{row.start_at}} 至 {{row.end_at}}</p></div><button class="reject" @click="action('/admin/bookings/'+row.id+'/cancel','POST',{reason:'管理员取消预约'},'预约已取消并已通知成员')">取消</button></div></article></div></section>
        <section v-if="active==='reviews' && isAdmin"><div class="page-head small"><div><p class="eyebrow">REVIEW CYCLE</p><h1>固定工位考察</h1><p>按自然日设置考察周期，系统会按周生成结构化周报任务。</p></div></div><div class="split-panels"><article class="panel"><h2>发起考察</h2><label>成员<select v-model="reviewForm.memberId"><option value="">选择拥有固定工位的正式成员</option><option v-for="m in members.filter(m=>m.seat_code&&m.member_status==='ACTIVE')" :value="m.id">{{m.name}} · {{m.seat_code}}</option></select></label><label>考察原因<textarea v-model="reviewForm.reason"></textarea></label><label>补充要求<textarea v-model="reviewForm.requirements"></textarea></label><label>开始日期<input v-model="reviewForm.startAt" type="date"></label><label>结束日期<input v-model="reviewForm.endAt" type="date"></label><button class="primary-action" :disabled="!reviewForm.memberId||!reviewForm.reason" @click="action('/admin/reviews','POST',reviewForm,'考察已发起，成员已转为考察成员')">发起考察</button></article><article class="panel wide"><h2>考察列表</h2><div class="table-scroll"><table><thead><tr><th>成员</th><th>周期</th><th>状态</th><th>人工决策</th></tr></thead><tbody><tr v-for="row in reviews" :key="row.id"><td><b>{{row.name}}</b><small>{{row.code}}</small><button class="mini" @click="openReports(row.id)">查看周报</button><button v-if="['PLANNED','ACTIVE','AWAITING_DECISION'].includes(row.status)" class="mini warn" @click="cancelReview(row)">取消考察</button></td><td>{{row.start_at.slice(5,10).replace('-','月')}}日<br>{{row.end_at.slice(5,10).replace('-','月')}}日</td><td><span class="status-chip">{{row.status}}</span></td><td v-if="row.status==='AWAITING_DECISION'"><button class="mini" @click="action('/admin/reviews/'+row.id+'/decision','POST',{result:'KEEP_SEAT',note:'管理员决定保留固定工位'},'已保留固定工位，成员已恢复正式成员')">保留</button><button class="mini" @click="action('/admin/reviews/'+row.id+'/decision','POST',{result:'EXEMPTED',note:'因特殊情况豁免'},'已记录豁免，成员已恢复正式成员')">豁免</button><button class="mini" @click="action('/admin/reviews/'+row.id+'/extend','POST',{endAt:reviewForm.endAt,note:'管理员延长考察'},'已延长考察，成员保持考察成员')">延长</button><button class="mini warn" @click="action('/admin/reviews/'+row.id+'/decision','POST',{result:'MOVE_TO_MOBILE',note:'管理员决定转为流动成员'},'已转为流动成员')">转流动</button></td><td v-else>{{row.result==='ADMIN_CANCELLED'?'管理员取消':row.result==='ACCOUNT_DELETED'?'账号删除':row.result||'进行中'}}</td></tr></tbody></table></div></article></div></section>
        <section v-if="active==='logs' && isAdmin"><div class="page-head small"><div><p class="eyebrow">AUDIT TRAIL</p><h1>审计日志</h1></div></div><article class="panel"><div class="table-scroll"><table><thead><tr><th>时间</th><th>操作者</th><th>动作</th><th>目标</th><th>说明</th></tr></thead><tbody><tr v-for="row in logs" :key="row.id"><td>{{row.created_at}}</td><td>{{row.actor_name||'系统'}}</td><td>{{row.action}}</td><td>{{row.target}}</td><td>{{row.detail}}</td></tr></tbody></table></div></article></section>
        <section v-if="active==='booking' && !isAdmin"><div class="page-head small"><div><p class="eyebrow">MOBILE SEAT BOOKING</p><h1>预约流动工位</h1><p>先查看占用情况，再选择工位与时间。单次最长 4 小时。</p></div><button class="outline-action" @click="loadAvailability">刷新可用时段</button></div><div class="booking-rules"><span><b>3 天内</b> 自动通过</span><span><b>3～7 天</b> 管理员审核</span><span><b>最长</b> 4 小时</span><span><b>同一时间</b> 仅可预约一个工位</span></div><article class="panel availability-panel"><div class="availability-head"><h2>未来 7 天工位占用</h2><span>仅显示时间段，不显示其他成员信息</span></div><div class="availability-grid"><div v-for="seat in availability.seats" :key="seat.id" class="availability-seat" :class="{chosen:String(bookingForm.seatId)===String(seat.id)}" @click="bookingForm.seatId=String(seat.id)"><div><b>{{seat.code}}</b><small>流动工位</small></div><div class="slot-list"><span v-for="item in availability.reservations.filter(item=>String(item.seat_id)===String(seat.id))" :key="item.id" :class="{mine:item.mine}">{{item.start_at.slice(5,16)}} ～ {{item.end_at.slice(5,16)}} {{item.mine?'我的预约':'已占用'}}</span><i v-if="!availability.reservations.filter(item=>String(item.seat_id)===String(seat.id)).length">未来 7 天暂无预约</i></div></div><p v-if="!availability.seats.length" class="empty">管理员尚未设置流动工位</p></div></article><div class="split-panels booking-layout"><article class="panel"><h2>创建预约</h2><label>流动工位<select v-model="bookingForm.seatId"><option value="">从上方可用性视图选择</option><option v-for="seat in mobileSeats" :value="seat.id">{{seat.code}} · {{seat.status}}</option></select></label><label>开始时间<input v-model="bookingForm.startAt" type="datetime-local"></label><label>结束时间<input v-model="bookingForm.endAt" type="datetime-local"></label><p class="booking-hint" :class="{bad:bookingHours>4||bookingConflict}"><template v-if="bookingConflict">所选工位在这个时间段已有预约，请选择其他时间或工位。</template><template v-else-if="bookingHours>4">当前时长 {{bookingHours.toFixed(1)}} 小时，超过 4 小时限制。</template><template v-else-if="bookingHours>0">当前预约 {{bookingHours.toFixed(1)}} 小时；{{new Date(bookingForm.startAt).getTime()>Date.now()+3*86400000?'将提交管理员审批':'将自动通过'}}。</template><template v-else>请选择有效时间段。</template></p><button class="primary-action" :disabled="!bookingForm.seatId||bookingHours<=0||bookingHours>4||bookingConflict" @click="action('/seat-bookings','POST',bookingForm,'预约已提交')">提交预约</button></article><article class="panel"><h2>我的预约</h2><div v-for="row in myBookings" :key="row.id" class="list-row"><div><b>{{row.code}} · {{row.status}}</b><p>{{row.start_at}} 至 {{row.end_at}}</p></div><button class="reject" v-if="['PENDING','APPROVED'].includes(row.status)" @click="action('/seat-bookings/'+row.id+'/cancel','POST',{},'预约已取消')">取消</button></div><p class="empty" v-if="!myBookings.length">暂无预约记录</p></article></div></section>
        <section v-if="active==='reports' && !isAdmin"><div class="page-head small"><div><p class="eyebrow">REVIEW MATERIALS</p><h1>考察周报</h1><p>周报按自然周开放：当周可填写，下一周不能提前提交。</p></div></div><div class="split-panels report-layout"><article class="panel task-panel"><h2>周报任务</h2><button v-for="task in tasks" :key="task.id" class="task-button" :class="{chosen:selectedTask?.id===task.id, future:!task.can_submit}" @click="openTask(task)"><b>第 {{task.period_index}} 周</b><span>{{task.period_start?.slice(5,10).replace('-','月')}}日开始 · 截止 {{task.due_at.slice(5,10).replace('-','月')}}日</span><small>{{task.can_submit?task.status:'未到当周'}}</small></button><p class="empty" v-if="!tasks.length">当前没有考察周报</p></article><article class="panel wide" v-if="selectedTask"><div class="report-heading"><div><h2>第 {{selectedTask.period_index}} 周材料</h2><p v-if="!selectedTaskCanSubmit">该周从 {{selectedTask.period_start?.slice(5,10).replace('-','月')}}日开始填写；当前不可提前填写。</p></div><span v-if="!selectedTaskCanSubmit" class="status-chip">未到当周</span></div><div class="report-grid" :class="{locked:!selectedTaskCanSubmit}"><template v-for="(section,key) in reportSections" :key="key"><article :class="{omitted:isSectionOmitted(section)}"><div class="report-section-head"><h3>{{reportTitles[key]}}</h3><button type="button" class="omit-button" :disabled="!selectedTaskCanSubmit" @click="toggleSectionOmitted(section)">{{isSectionOmitted(section)?'取消省略':'⋯ 省略'}}</button></div><p v-if="isSectionOmitted(section)" class="omitted-copy">本项将按“无”填写，点击保存草稿或正式提交后生效。</p><template v-else><label v-if="['competition','horizontalProject','verticalProject'].includes(key)">从已加入项目填写<select :disabled="!selectedTaskCanSubmit" @change="fillProject(section,$event.target.value)"><option value="">选择项目（可选）</option><option v-for="p in joinedProjects.filter(p=>p.type===({competition:'COMPETITION',horizontalProject:'HORIZONTAL',verticalProject:'VERTICAL'}[key]))" :value="p.id">{{p.name}}</option></select></label><input v-model="section.title" :disabled="!selectedTaskCanSubmit" placeholder="标题 / 名称"><textarea v-model="section.detail" :disabled="!selectedTaskCanSubmit" placeholder="详细说明"></textarea><input v-if="'collaborators' in section" v-model="section.collaborators" :disabled="!selectedTaskCanSubmit" placeholder="协作实验室同学（可填无协作同学）"><input v-if="key==='outcome'" v-model="section.url" :disabled="!selectedTaskCanSubmit" placeholder="成果链接（可选）"></template></article></template></div><div class="form-actions"><button class="outline-action" :disabled="!selectedTaskCanSubmit" @click="saveReport('save')">保存草稿</button><button class="primary-action compact" :disabled="!selectedTaskCanSubmit" @click="saveReport('submit')">正式提交</button></div></article><article class="panel wide" v-else><p class="empty">从左侧选择一个周报任务开始填写</p></article></div></section>
        <section v-if="active==='special' && !isAdmin"><div class="page-head small"><div><p class="eyebrow">SPECIAL CIRCUMSTANCES</p><h1>特殊情况登记</h1></div></div><div class="split-panels"><article class="panel"><label>类型<select v-model="circumstanceForm.type"><option>考试或保研准备</option><option>实习</option><option>学科竞赛</option><option>科研任务</option><option>生病或个人紧急情况</option><option>其他</option></select></label><label>开始时间<input v-model="circumstanceForm.startAt" type="datetime-local"></label><label>结束时间<input v-model="circumstanceForm.endAt" type="datetime-local"></label><label>说明<textarea v-model="circumstanceForm.description"></textarea></label><label>证明链接（可选）<input v-model="circumstanceForm.evidenceUrl"></label><button class="primary-action" :disabled="!circumstanceForm.description" @click="action('/special-circumstances','POST',circumstanceForm,'特殊情况已登记')">保存登记</button></article><article class="panel"><h2>历史记录</h2><div v-for="row in circumstances" :key="row.id" class="list-row"><div><b>{{row.type}}</b><p>{{row.start_at}} 至 {{row.end_at}}<br>{{row.description}}</p></div></div><p class="empty" v-if="!circumstances.length">暂无特殊情况记录</p></article></div></section>
        <section v-if="active==='notices' && !isAdmin"><div class="page-head small"><div><p class="eyebrow">INBOX</p><h1>站内信</h1></div></div><article class="panel"><div v-for="notice in notices" :key="notice.id" class="notice-row" :class="{unread:!notice.read_flag}" @click="action('/notifications/'+notice.id+'/read','POST',{},'已标记为已读')"><b>{{notice.title}}</b><p>{{notice.content}}</p><small>{{notice.created_at}}</small></div><p class="empty" v-if="!notices.length">暂无站内信</p></article></section>
      </section>
    </section>
  </main>`
};
createApp(App).mount('#app');
