import { computed, onMounted, ref, watch } from 'vue';
import './management.css';
export default {
  props:['request','user'],emits:['changed'],
  setup(props:any,{emit}:any){
    const members=ref<any[]>([]),pending=ref<any[]>([]),selected=ref<number[]>([]),q=ref(''),busy=ref(false),error=ref(''),message=ref(''),tab=ref('pending');
    const removal=ref<any>(null),confirmation=ref(''),reason=ref('');
    const labels:Record<string,string>={MOBILE:'流动成员',ACTIVE:'正式成员',REVIEW:'考察成员',UNCONFIRMED:'未确认',DELETED:'已删除'};
    const matches=(m:any)=>(m.name+' '+m.student_no).includes(q.value.trim());
    const visiblePending=computed(()=>pending.value.filter(matches));const visibleMembers=computed(()=>members.value.filter(matches));
    const load=async()=>{[members.value,pending.value]=await Promise.all([props.request('/admin/members'),props.request('/admin/registrations')]);selected.value=selected.value.filter(id=>pending.value.some(m=>m.id===id));};
    const run=async(fn:()=>Promise<void>)=>{if(busy.value)return;busy.value=true;error.value='';message.value='';try{await fn();}catch(e:any){error.value=e.message;}finally{busy.value=false;}};
    const refresh=()=>run(load);
    const post=async(path:string,body:any)=>{const result=await props.request(path,{method:'POST',body:JSON.stringify(body)});message.value=result.message;await load();emit('changed');};
    const allSelected=computed(()=>visiblePending.value.length>0 && visiblePending.value.every(m=>selected.value.includes(m.id)));
    const toggleAll=()=>{selected.value=allSelected.value?[]:visiblePending.value.slice(0,500).map(m=>m.id);};
    const approve=()=>{if(!selected.value.length)return;if(!window.confirm(`确认通过所选 ${selected.value.length} 人的注册申请？`))return;run(async()=>{await post('/admin/registrations/batch-approve',{ids:[...selected.value]});selected.value=[];});};
    const singleApprove=(m:any)=>run(()=>post('/admin/registrations/'+m.id+'/approve',{}));
    const reject=(m:any)=>{const text=window.prompt('请输入拒绝 '+m.name+' 注册的原因');if(!text?.trim())return;run(()=>post('/admin/registrations/'+m.id+'/reject',{reason:text.trim()}));};
    const openDelete=(m:any)=>run(async()=>{removal.value=await props.request('/admin/members/'+m.id+'/delete-preview');confirmation.value='';reason.value='';});
    const deleteUser=()=>run(async()=>{await post('/admin/members/'+removal.value.user.id+'/delete',{confirmStudentNo:confirmation.value,reason:reason.value.trim()});removal.value=null;});
    watch(q,()=>{selected.value=[];});onMounted(refresh);
    return{members,pending,selected,q,busy,error,message,tab,removal,confirmation,reason,labels,visiblePending,visibleMembers,allSelected,toggleAll,approve,singleApprove,reject,openDelete,deleteUser,refresh};
  },
  template:`<section class="management" :aria-busy="busy"><header class="mg-heading"><div><p class="mg-kicker">实验室 / 成员治理</p><h1>成员管理</h1><p>审核注册、查看成员状态，安全处理离开实验室的账号。</p></div><button class="mg-button" :disabled="busy" @click="refresh">刷新</button></header><p v-if="error" class="mg-alert" role="alert">{{error}}</p><p v-if="message" class="mg-notice" role="status">{{message}}</p>
  <form v-if="removal" class="mg-surface member-delete" @submit.prevent="deleteUser"><h2>确认删除 {{removal.user.name}} 的账号</h2><p class="mg-alert">账号将无法登录，已有登录会话将失效。工位、有效预约和未结束项目中的成员席位会释放；周报、已结束项目和审计记录保留。学号保留，不能以相同学号重新注册。</p><dl class="mg-facts"><div><dt>固定工位</dt><dd>{{removal.seats}}</dd></div><div><dt>有效预约</dt><dd>{{removal.bookings}}</dd></div><div><dt>保留周报</dt><dd>{{removal.reports}}</dd></div><div><dt>移出进行中团队</dt><dd>{{removal.teams}}</dd></div></dl><p v-if="removal.ownedProjects" class="mg-alert">此人负责 {{removal.ownedProjects}} 个未结束项目，请先结束项目再删除账号。</p><label>输入学号 {{removal.user.student_no}} 确认<input v-model="confirmation" :disabled="busy" autocomplete="off" required></label><label>删除原因<textarea v-model="reason" :disabled="busy" required maxlength="500" rows="3"></textarea></label><div class="mg-form-footer"><button type="button" class="mg-button" :disabled="busy" @click="removal=null">取消</button><button class="mg-button danger" :disabled="busy||!!removal.ownedProjects||confirmation!==removal.user.student_no||!reason.trim()">确认删除账号</button></div></form>
  <template v-else><nav class="mg-tabs" aria-label="成员分类"><button :aria-current="tab==='pending'?'page':null" @click="tab='pending'">注册审核 <span>{{pending.length}}</span></button><button :aria-current="tab==='members'?'page':null" @click="tab='members'">成员档案 <span>{{members.length}}</span></button></nav><div class="mg-filters"><label class="mg-search">成员搜索<input v-model="q" placeholder="姓名或学号" :disabled="busy"></label></div>
  <template v-if="tab==='pending'"><div class="member-bulk"><button class="mg-button" :disabled="busy||!visiblePending.length" @click="toggleAll">{{allSelected?'取消全选':'全选待审核'}}</button><span>已选 {{selected.length}} / 当前 {{visiblePending.length}} 人</span><button class="mg-button primary" :disabled="busy||!selected.length" @click="approve">通过所选（{{selected.length}}）</button></div><p v-if="visiblePending.length>500" class="mg-notice">单批最多审核 500 人，全选会选中当前结果的前 500 人。</p><div class="mg-table-wrap"><table class="mg-table"><thead><tr><th>选择</th><th>申请人</th><th>注册时间</th><th>操作</th></tr></thead><tbody><tr v-for="m in visiblePending" :key="m.id"><td><input class="member-check" type="checkbox" v-model="selected" :value="m.id" :disabled="busy||(!selected.includes(m.id)&&selected.length>=500)" :aria-label="'选择 '+m.name+' '+m.student_no"></td><td><b>{{m.name}}</b><small>{{m.student_no}}</small></td><td>{{m.created_at}}</td><td><button class="mg-link" :disabled="busy" @click="singleApprove(m)">通过</button>　<button class="mg-link danger" :disabled="busy" @click="reject(m)">拒绝</button></td></tr></tbody></table><p v-if="!visiblePending.length" class="mg-empty">暂无符合条件的待审核注册</p></div></template>
  <div v-else class="mg-table-wrap member-table"><table class="mg-table"><thead><tr><th>姓名 / 学号</th><th>账号状态</th><th>成员身份</th><th>固定工位</th><th>账号操作</th></tr></thead><tbody><tr v-for="m in visibleMembers" :key="m.id"><td><b>{{m.name}}</b><small>{{m.student_no}}</small></td><td>{{m.approved===1?'已审核':m.approved===0?'待审核':'已拒绝'}}</td><td>{{m.role==='ADMIN'?'管理员':labels[m.member_status]||m.member_status}}</td><td>{{m.seat_code||'—'}}</td><td><button v-if="m.role!=='ADMIN'&&m.id!==user.id" class="mg-link danger" :disabled="busy" @click="openDelete(m)">删除用户</button><span v-else class="mg-muted">受保护</span></td></tr></tbody></table><p v-if="!visibleMembers.length" class="mg-empty">没有符合条件的成员</p></div></template></section>`
};
