import { computed, onMounted, ref } from 'vue';
import './management.css';

export default {
  props: ['request', 'user', 'members'],
  emits: ['changed'],
  setup(props: any, { emit }: any) {
    const items = ref<any[]>([]), total = ref(0), page = ref(1), q = ref(''), status = ref('');
    const detail = ref<any>(null), busy = ref(false), error = ref(''), message = ref(''), editing = ref(false), editId = ref<number|null>(null);
    const blank = () => ({ name: '', type: 'COMPETITION', description: '', requirements: '', capacity: 5, deadline: '' });
    const draft = ref(blank()), application = ref({ reason: '', skills: '', availability: '' }), memberId = ref(''), reviewNotes = ref<Record<string,string>>({});
    const admin = computed(() => props.user?.role === 'ADMIN');
    const canPublish = computed(() => admin.value || (props.user?.approved===1 && ['MOBILE','ACTIVE','REVIEW'].includes(props.user?.member_status)));
    const canManage = computed(() => admin.value || detail.value?.can_manage===true);
    const sort = ref('newest');
    const published = (date:string) => { if(!date)return '—'; const value=new Date(date.replace(' ','T')+'Z');return Number.isNaN(value.getTime())?date:new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(value); };
    const pane = ref('overview');
    const pendingCount = computed(() => detail.value?.applications.filter((a:any)=>a.status==='PENDING').length || 0);
    const applicationFilter = ref('PENDING');
    const shownApplications = computed(() => detail.value?.applications.filter((a:any)=>!canManage.value || !applicationFilter.value || a.status===applicationFilter.value) || []);
    const deadlinePassed = (date:string) => date < new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
    const projectStatus = (p:any) => p.status==='RECRUITING' && deadlinePassed(p.deadline) ? '申请已截止' : labels[p.status];
    const unavailableReason = computed(() => {
      if (!detail.value) return '';
      if (detail.value.team.some((m:any)=>m.id===props.user?.id)) return '你已加入这个团队，可在团队成员中查看协作同学。';
      if (detail.value.applications.some((a:any)=>a.status==='PENDING')) return '你的申请正在审核中，可在“我的申请”中查看或撤回。';
      if (!['MOBILE','ACTIVE','REVIEW'].includes(props.user?.member_status)) return '账号经管理员确认后，即可申请加入项目。';
      if (detail.value.project.status!=='RECRUITING' || deadlinePassed(detail.value.project.deadline)) return '本项目当前不接受新的加入申请。';
      return '团队人数已满，暂不接受新的加入申请。';
    });
    const labels: Record<string,string> = { COMPETITION: '学科竞赛', HORIZONTAL: '横向课题', VERTICAL: '纵向课题', OTHER: '其他项目', RECRUITING: '招募中', CLOSED: '招募关闭', COMPLETED: '已结束', PENDING: '待审核', APPROVED: '已通过', REJECTED: '未通过', WITHDRAWN: '已撤回' };
    const availableMembers = computed(() => (props.members || []).filter((m:any) => m.role === 'MEMBER' && m.approved && ['MOBILE','ACTIVE','REVIEW'].includes(m.member_status) && !detail.value?.team.some((t:any) => t.id === m.id)));
    const canApply = computed(() => !admin.value && ['MOBILE','ACTIVE','REVIEW'].includes(props.user?.member_status) && detail.value?.project.status === 'RECRUITING' && detail.value.project.deadline >= new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10) && detail.value.team.length < detail.value.project.capacity && !detail.value.team.some((m:any) => m.id === props.user.id) && !detail.value.applications.some((a:any) => a.status === 'PENDING'));
    const load = async () => { const result = await props.request(`/projects?q=${encodeURIComponent(q.value)}&status=${status.value}&page=${page.value}&sort=${sort.value}`); items.value = result.items; total.value = result.total; };
    const run = async (fn:()=>Promise<void>) => { if (busy.value) return; busy.value = true; error.value = ''; message.value = ''; try { await fn(); } catch(e:any) { error.value = e.message; } finally { busy.value = false; } };
    const search = (next = 1) => run(async () => { page.value = next; await load(); });
    const open = (id:number) => run(async () => { detail.value = await props.request(`/projects/${id}`); pane.value='overview'; applicationFilter.value='PENDING'; memberId.value=''; editing.value = false; reviewNotes.value = {}; application.value = { reason:'', skills:'', availability:'' }; });
    const mutate = (suffix:string, body:any = {}) => run(async () => { const id = detail.value.project.id; const result = await props.request(`/projects/${id}${suffix}`, { method:'POST', body:JSON.stringify(body) }); message.value = result.message; detail.value = await props.request(`/projects/${id}`); await load(); emit('changed'); });
    const edit = (existing = false) => { error.value = ''; editId.value = existing ? detail.value.project.id : null; draft.value = existing ? { ...detail.value.project } : blank(); editing.value = true; };
    const save = () => run(async () => { const result = await props.request(editId.value ? `/projects/${editId.value}/edit` : '/projects', { method:'POST', body:JSON.stringify(draft.value) }); detail.value = await props.request(`/projects/${editId.value || result.id}`); editing.value = false; message.value = result.message; await load(); emit('changed'); });
    const changeStatus = (value:string) => { if(value === 'COMPLETED' && !window.confirm('结束项目后不可恢复，待审核申请将关闭。确认结束？')) return; mutate('/status', {status:value}); };
    const remove = (m:any) => { if(window.confirm(`确认将 ${m.name} 移出团队？`)) mutate(`/members/${m.id}/remove`); };
    onMounted(() => search());
    return { canPublish,canManage,sort,published,pane,pendingCount,applicationFilter,shownApplications,projectStatus,unavailableReason,items,total,page,q,status,detail,busy,error,message,editing,draft,application,memberId,reviewNotes,admin,labels,availableMembers,canApply,search,open,mutate,edit,save,changeStatus,remove };
  },
  template: `<section class="management projects-page" :aria-busy="busy">
    <header class="mg-heading"><div><p class="mg-kicker">实验室 / 协作空间</p><h1>{{detail&&!editing?detail.project.name:'项目团队'}}</h1><p>{{admin?'浏览项目、组建团队，集中处理成员的加入申请。':'寻找感兴趣的竞赛与课题，和实验室同学一起协作。'}}</p></div><button v-if="canPublish&&!detail&&!editing" class="mg-button primary" :disabled="busy" @click="edit()">＋ {{admin?'发布项目':'发布竞赛招募'}}</button></header>
    <p v-if="error" class="mg-alert" role="alert">{{error}}</p><p v-if="message" class="mg-notice" role="status">{{message}}</p>
    <fieldset :disabled="busy" class="mg-controls">
    <form v-if="editing" class="project-editor mg-surface" @submit.prevent="save"><div class="mg-section-title"><h2>{{draft.id?'编辑项目':'发布新项目'}}</h2><span>填写清晰的介绍，帮助成员判断是否适合加入</span></div><p v-if="!admin" class="mg-notice">发布者自动加入团队并计入人数上限。你可编辑和管理自己发布的竞赛；报名材料对申请人、发布者和管理员可见。</p><label>项目名称<input v-model="draft.name" placeholder="例如：全国大学生智能车竞赛" required maxlength="100"></label><div class="mg-form-grid"><label>项目类型<select v-model="draft.type"><option v-for="t in (admin?['COMPETITION','HORIZONTAL','VERTICAL','OTHER']:['COMPETITION'])" :value="t">{{labels[t]}}</option></select></label><label>团队人数上限<input type="number" v-model.number="draft.capacity" min="1" max="200" required></label><label>申请截止日期<input type="date" v-model="draft.deadline" required></label></div><label>项目介绍<textarea v-model="draft.description" placeholder="项目目标、主要任务和预期成果" required maxlength="6000" rows="5"></textarea></label><label>招募要求<textarea v-model="draft.requirements" placeholder="需要的技能、适合的同学和时间投入" required maxlength="3000" rows="4"></textarea></label><footer class="mg-form-footer"><button type="button" class="mg-button" @click="editing=false">取消</button><button class="mg-button primary">{{draft.id?'保存修改':'发布项目'}}</button></footer></form>
    <template v-else-if="detail"><button class="mg-link mg-back" @click="detail=null">← 所有项目</button><div class="project-summary"><span class="mg-type">{{labels[detail.project.type]}}</span><span class="mg-status" :data-status="detail.project.status">{{projectStatus(detail.project)}}</span><span>{{detail.project.creator_name}} · 发布于 {{published(detail.project.created_at)}}</span><span>申请截止 {{detail.project.deadline}}</span><span>团队 {{detail.team.length}} / {{detail.project.capacity}} 人</span></div>
    <nav class="mg-tabs" aria-label="项目详情"><button :aria-current="pane==='overview'?'page':null" @click="pane='overview'">项目概况</button><button :aria-current="pane==='team'?'page':null" @click="pane='team'">团队成员 <span>{{detail.team.length}}</span></button><button :aria-current="pane==='applications'?'page':null" @click="pane='applications'">{{canManage?'报名审核':'我的申请'}} <span v-if="pendingCount">{{pendingCount}}</span></button></nav>
    <div v-if="pane==='overview'" class="project-overview"><article class="mg-surface project-brief"><section><p class="mg-kicker">项目目标</p><h2>一起完成什么</h2><p class="mg-prose">{{detail.project.description}}</p></section><section><p class="mg-kicker">招募要求</p><h2>期待怎样的伙伴</h2><p class="mg-prose">{{detail.project.requirements}}</p></section></article><aside class="mg-surface project-side"><h2>团队招募</h2><div class="project-capacity"><strong>{{detail.team.length}}</strong><span>/ {{detail.project.capacity}} 人</span></div><progress :value="detail.team.length" :max="detail.project.capacity" aria-label="团队人数"></progress><p class="mg-muted">项目成员身份不改变工位或考察状态。</p><template v-if="canManage"><button class="mg-button" @click="pane='applications'">查看报名 <span>{{pendingCount}} 待审</span></button><template v-if="detail.project.status!=='COMPLETED'"><button class="mg-button" @click="edit(true)">编辑项目资料</button><button class="mg-button" @click="changeStatus(detail.project.status==='RECRUITING'?'CLOSED':'RECRUITING')">{{detail.project.status==='RECRUITING'?'关闭招募':'重新开放招募'}}</button><div class="project-danger"><p>结束后保留团队记录，关闭待审核申请，且不可恢复。</p><button class="mg-link danger" @click="changeStatus('COMPLETED')">结束项目</button></div></template></template><template v-else><button v-if="canApply" class="mg-button primary" @click="pane='applications'">申请加入 →</button><p v-else class="mg-notice">{{unavailableReason}}</p></template></aside></div>
    <section v-if="pane==='team'" class="mg-surface"><div class="mg-section-title"><h2>团队成员</h2><span>仅展示姓名，不公开个人周报与成果</span></div><div class="project-members"><article v-for="m in detail.team" :key="m.id" class="project-member"><span class="member-avatar">{{m.name.slice(0,1)}}</span><div><b>{{m.name}}</b><small>{{m.joined_at?.slice(0,10)}} 加入</small></div><button v-if="canManage&&m.id!==detail.project.created_by&&detail.project.status!=='COMPLETED'" class="mg-link danger" @click="remove(m)">移出团队</button></article></div><div v-if="!detail.team.length" class="mg-empty"><h3>团队正在组建</h3><p>{{admin?'通过报名审核或下方直接添加成员。':'申请通过后，你的姓名会出现在这里。'}}</p></div><form v-if="admin&&detail.project.status!=='COMPLETED'" class="project-add-member" @submit.prevent="mutate('/members',{memberId:Number(memberId)})"><label>直接添加成员<select v-model="memberId" required><option value="">选择已确认的实验室成员</option><option v-for="m in availableMembers" :value="m.id">{{m.name}} · {{m.student_no}}</option></select></label><button class="mg-button primary" :disabled="!memberId||detail.team.length>=detail.project.capacity">添加到团队</button></form></section>
    <section v-if="pane==='applications'" class="mg-surface"><div class="mg-section-title"><h2>{{canManage?'报名审核':'我的申请'}}</h2><label v-if="canManage" class="application-filter">筛选<select v-model="applicationFilter"><option value="">全部记录</option><option v-for="s in ['PENDING','APPROVED','REJECTED','WITHDRAWN']" :value="s">{{labels[s]}}</option></select></label></div><form v-if="canApply" class="project-apply" @submit.prevent="mutate('/apply',application)"><p class="mg-muted">申请内容仅你、项目发布者和管理员可见。</p><label>为什么想加入<textarea v-model="application.reason" required maxlength="2000" rows="3"></textarea></label><div class="mg-form-grid two"><label>已有技能<textarea v-model="application.skills" required maxlength="2000" rows="3"></textarea></label><label>可投入时间<textarea v-model="application.availability" required maxlength="1000" rows="3"></textarea></label></div><button class="mg-button primary">提交加入申请</button></form><p v-else-if="!canManage" class="mg-notice">{{unavailableReason}}</p><article v-for="a in shownApplications" :key="a.id" class="application-record"><header><div><b>{{a.name||user.name}}</b><small>{{a.created_at?.slice(0,16).replace('T',' ')}}</small></div><span class="mg-status" :data-status="a.status">{{labels[a.status]}}</span></header><dl class="application-content"><div><dt>申请理由</dt><dd>{{a.reason}}</dd></div><div><dt>已有技能</dt><dd>{{a.skills}}</dd></div><div><dt>可投入时间</dt><dd>{{a.availability}}</dd></div></dl><p v-if="a.review_note" class="mg-notice">审核备注：{{a.review_note}}</p><template v-if="a.status==='PENDING'"><template v-if="canManage"><label>审核备注（可选）<textarea v-model="reviewNotes[a.id]" maxlength="2000" rows="2" placeholder="给申请人的反馈"></textarea></label><div class="mg-form-footer"><button class="mg-button danger" @click="mutate('/applications/'+a.id+'/decision',{decision:'reject',note:reviewNotes[a.id]||''})">拒绝申请</button><button class="mg-button primary" :disabled="detail.team.length>=detail.project.capacity" @click="mutate('/applications/'+a.id+'/decision',{decision:'approve',note:reviewNotes[a.id]||''})">通过并加入团队</button></div><p v-if="detail.team.length>=detail.project.capacity" class="mg-muted">团队人数已满，请先调整容量或团队成员。</p></template><button v-else class="mg-button" @click="mutate('/applications/'+a.id+'/withdraw')">撤回申请</button></template></article><div v-if="!shownApplications.length&&!canApply" class="mg-empty"><h3>{{canManage?'当前筛选下没有申请':'暂无申请记录'}}</h3><p>{{canManage?'可切换为全部记录，查看已处理的报名。':'开放招募且符合条件时，可以在此填写申请。'}}</p></div></section>
    </template>
    <template v-else><form class="mg-filters" @submit.prevent="search()"><label class="mg-search">项目名称<input v-model="q" placeholder="搜索竞赛或课题名称" maxlength="100"></label><label>项目状态<select v-model="status"><option value="">全部状态</option><option v-for="s in ['RECRUITING','CLOSED','COMPLETED']" :value="s">{{labels[s]}}</option></select></label><label>发布时间排序<select v-model="sort" @change="search()"><option value="newest">最新发布在前</option><option value="oldest">最早发布在前</option></select></label><button class="mg-button primary">查询项目</button><button type="button" class="mg-button" @click="search(page)">刷新</button></form><div class="mg-results-bar"><span>{{busy?'正在加载…':'共 '+total+' 个项目'}}</span><span>竞赛 · 横向课题 · 纵向课题</span></div><div class="project-directory"><article v-for="p in items" :key="p.id" class="project-directory-row"><div class="project-directory-main"><span class="mg-type">{{labels[p.type]}}</span><h2><button class="mg-title-button" @click="open(p.id)">{{p.name}}</button></h2><p>{{p.description}}</p><small>{{p.creator_name||'实验室'}} · 发布于 {{published(p.created_at)}}<br>申请截止 {{p.deadline}}<span v-if="p.joined"> · 你已加入团队</span></small></div><div class="project-directory-capacity"><span>团队规模</span><strong>{{p.member_count}} <small>/ {{p.capacity}}</small></strong><progress :value="p.member_count" :max="p.capacity" aria-label="团队人数"></progress></div><div class="project-directory-action"><span class="mg-status" :data-status="p.status">{{projectStatus(p)}}</span><button class="mg-link" @click="open(p.id)">查看项目 →</button></div></article><div v-if="!items.length&&!busy" class="mg-empty"><h2>暂无符合条件的项目</h2><p>{{admin?'发布第一个项目，或调整搜索条件。':'试试其他名称或状态，也可以稍后再来查看。'}}</p></div></div><nav class="mg-pagination" aria-label="项目分页"><span>第 {{page}} 页</span><button class="mg-button" :disabled="page<=1" @click="search(page-1)">上一页</button><button class="mg-button" :disabled="page*12>=total" @click="search(page+1)">下一页</button></nav></template>
    </fieldset></section>`
};
